#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

. config/options linux

${SCRIPTS}/unpack linux

if [ -f "${DISTRO_DIR}/${DISTRO}/required_kernel_options" ]; then
  while read OPTION; do
    [ -z "$OPTION" -o -n "$(echo "$OPTION" | grep '^#')" ] && continue

    if [ "${OPTION##*=}" == "m" ]; then
      echo "[m] ${OPTION%%=*}"
      $PKG_BUILD/scripts/config --file $PKG_KERNEL_CFG_FILE --module ${OPTION%%=*}
    fi

    if [ "${OPTION##*=}" == "y" ]; then
      echo "[y] ${OPTION%%=*}"
      $PKG_BUILD/scripts/config --file $PKG_KERNEL_CFG_FILE --enable ${OPTION%%=*}
    fi
  done < ${DISTRO_DIR}/${DISTRO}/required_kernel_options
else
  echo "required kernel options file doesn't exist: ${DISTRO_DIR}/${DISTRO}/required_kernel_options"
fi

if [ -f "${DISTRO_DIR}/${DISTRO}/optional_kernel_options" ]; then
  while read OPTION; do
    [ -z "$OPTION" -o -n "$(echo "$OPTION" | grep '^#')" ] && continue

    if [ "${OPTION##*=}" == "m" ]; then
      echo "[m] ${OPTION%%=*}"
      $PKG_BUILD/scripts/config --file $PKG_KERNEL_CFG_FILE --module ${OPTION%%=*}
    fi

    if [ "${OPTION##*=}" == "y" ]; then
      echo "[y] ${OPTION%%=*}"
      $PKG_BUILD/scripts/config --file $PKG_KERNEL_CFG_FILE --enable ${OPTION%%=*}
    fi
  done < ${DISTRO_DIR}/${DISTRO}/optional_kernel_options
else
  echo "optional kernel options file doesn't exist: ${DISTRO_DIR}/${DISTRO}/optional_kernel_options"
fi
